/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SuccessRouteImport } from './routes/success'
import { Route as OverlayRouteImport } from './routes/overlay'
import { Route as InlineRouteImport } from './routes/inline'
import { Route as FailureRouteImport } from './routes/failure'
import { Route as ActionSheetRouteImport } from './routes/action-sheet'
import { Route as IndexRouteImport } from './routes/index'
<<<<<<< HEAD
import { Route as OverlayProfileRouteImport } from './routes/overlay/profile'
import { Route as OverlayPaymentRouteImport } from './routes/overlay/payment'
=======
>>>>>>> main
import { Route as InlineProfileRouteImport } from './routes/inline/profile'
import { Route as InlinePaymentRouteImport } from './routes/inline/payment'

const SuccessRoute = SuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => rootRouteImport,
} as any)
const OverlayRoute = OverlayRouteImport.update({
  id: '/overlay',
  path: '/overlay',
  getParentRoute: () => rootRouteImport,
} as any)
const InlineRoute = InlineRouteImport.update({
  id: '/inline',
  path: '/inline',
  getParentRoute: () => rootRouteImport,
} as any)
const FailureRoute = FailureRouteImport.update({
  id: '/failure',
  path: '/failure',
  getParentRoute: () => rootRouteImport,
} as any)
const ActionSheetRoute = ActionSheetRouteImport.update({
  id: '/action-sheet',
  path: '/action-sheet',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
<<<<<<< HEAD
const OverlayProfileRoute = OverlayProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => OverlayRoute,
} as any)
const OverlayPaymentRoute = OverlayPaymentRouteImport.update({
  id: '/payment',
  path: '/payment',
  getParentRoute: () => OverlayRoute,
} as any)
=======
>>>>>>> main
const InlineProfileRoute = InlineProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => InlineRoute,
} as any)
const InlinePaymentRoute = InlinePaymentRouteImport.update({
  id: '/payment',
  path: '/payment',
  getParentRoute: () => InlineRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/action-sheet': typeof ActionSheetRoute
  '/failure': typeof FailureRoute
  '/inline': typeof InlineRouteWithChildren
<<<<<<< HEAD
  '/overlay': typeof OverlayRouteWithChildren
  '/success': typeof SuccessRoute
  '/inline/payment': typeof InlinePaymentRoute
  '/inline/profile': typeof InlineProfileRoute
  '/overlay/payment': typeof OverlayPaymentRoute
  '/overlay/profile': typeof OverlayProfileRoute
=======
  '/overlay': typeof OverlayRoute
  '/success': typeof SuccessRoute
  '/inline/payment': typeof InlinePaymentRoute
  '/inline/profile': typeof InlineProfileRoute
>>>>>>> main
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/action-sheet': typeof ActionSheetRoute
  '/failure': typeof FailureRoute
  '/inline': typeof InlineRouteWithChildren
<<<<<<< HEAD
  '/overlay': typeof OverlayRouteWithChildren
  '/success': typeof SuccessRoute
  '/inline/payment': typeof InlinePaymentRoute
  '/inline/profile': typeof InlineProfileRoute
  '/overlay/payment': typeof OverlayPaymentRoute
  '/overlay/profile': typeof OverlayProfileRoute
=======
  '/overlay': typeof OverlayRoute
  '/success': typeof SuccessRoute
  '/inline/payment': typeof InlinePaymentRoute
  '/inline/profile': typeof InlineProfileRoute
>>>>>>> main
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/action-sheet': typeof ActionSheetRoute
  '/failure': typeof FailureRoute
  '/inline': typeof InlineRouteWithChildren
<<<<<<< HEAD
  '/overlay': typeof OverlayRouteWithChildren
  '/success': typeof SuccessRoute
  '/inline/payment': typeof InlinePaymentRoute
  '/inline/profile': typeof InlineProfileRoute
  '/overlay/payment': typeof OverlayPaymentRoute
  '/overlay/profile': typeof OverlayProfileRoute
=======
  '/overlay': typeof OverlayRoute
  '/success': typeof SuccessRoute
  '/inline/payment': typeof InlinePaymentRoute
  '/inline/profile': typeof InlineProfileRoute
>>>>>>> main
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/action-sheet'
    | '/failure'
    | '/inline'
    | '/overlay'
    | '/success'
    | '/inline/payment'
    | '/inline/profile'
<<<<<<< HEAD
    | '/overlay/payment'
    | '/overlay/profile'
=======
>>>>>>> main
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/action-sheet'
    | '/failure'
    | '/inline'
    | '/overlay'
    | '/success'
    | '/inline/payment'
    | '/inline/profile'
<<<<<<< HEAD
    | '/overlay/payment'
    | '/overlay/profile'
=======
>>>>>>> main
  id:
    | '__root__'
    | '/'
    | '/action-sheet'
    | '/failure'
    | '/inline'
    | '/overlay'
    | '/success'
    | '/inline/payment'
    | '/inline/profile'
<<<<<<< HEAD
    | '/overlay/payment'
    | '/overlay/profile'
=======
>>>>>>> main
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActionSheetRoute: typeof ActionSheetRoute
  FailureRoute: typeof FailureRoute
  InlineRoute: typeof InlineRouteWithChildren
<<<<<<< HEAD
  OverlayRoute: typeof OverlayRouteWithChildren
=======
  OverlayRoute: typeof OverlayRoute
>>>>>>> main
  SuccessRoute: typeof SuccessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/success': {
      id: '/success'
      path: '/success'
      fullPath: '/success'
      preLoaderRoute: typeof SuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/overlay': {
      id: '/overlay'
      path: '/overlay'
      fullPath: '/overlay'
      preLoaderRoute: typeof OverlayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inline': {
      id: '/inline'
      path: '/inline'
      fullPath: '/inline'
      preLoaderRoute: typeof InlineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/failure': {
      id: '/failure'
      path: '/failure'
      fullPath: '/failure'
      preLoaderRoute: typeof FailureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/action-sheet': {
      id: '/action-sheet'
      path: '/action-sheet'
      fullPath: '/action-sheet'
      preLoaderRoute: typeof ActionSheetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
<<<<<<< HEAD
    '/overlay/profile': {
      id: '/overlay/profile'
      path: '/profile'
      fullPath: '/overlay/profile'
      preLoaderRoute: typeof OverlayProfileRouteImport
      parentRoute: typeof OverlayRoute
    }
    '/overlay/payment': {
      id: '/overlay/payment'
      path: '/payment'
      fullPath: '/overlay/payment'
      preLoaderRoute: typeof OverlayPaymentRouteImport
      parentRoute: typeof OverlayRoute
    }
=======
>>>>>>> main
    '/inline/profile': {
      id: '/inline/profile'
      path: '/profile'
      fullPath: '/inline/profile'
      preLoaderRoute: typeof InlineProfileRouteImport
      parentRoute: typeof InlineRoute
    }
    '/inline/payment': {
      id: '/inline/payment'
      path: '/payment'
      fullPath: '/inline/payment'
      preLoaderRoute: typeof InlinePaymentRouteImport
      parentRoute: typeof InlineRoute
    }
  }
}

interface InlineRouteChildren {
  InlinePaymentRoute: typeof InlinePaymentRoute
  InlineProfileRoute: typeof InlineProfileRoute
}

const InlineRouteChildren: InlineRouteChildren = {
  InlinePaymentRoute: InlinePaymentRoute,
  InlineProfileRoute: InlineProfileRoute,
}

const InlineRouteWithChildren =
  InlineRoute._addFileChildren(InlineRouteChildren)

<<<<<<< HEAD
interface OverlayRouteChildren {
  OverlayPaymentRoute: typeof OverlayPaymentRoute
  OverlayProfileRoute: typeof OverlayProfileRoute
}

const OverlayRouteChildren: OverlayRouteChildren = {
  OverlayPaymentRoute: OverlayPaymentRoute,
  OverlayProfileRoute: OverlayProfileRoute,
}

const OverlayRouteWithChildren =
  OverlayRoute._addFileChildren(OverlayRouteChildren)

=======
>>>>>>> main
const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActionSheetRoute: ActionSheetRoute,
  FailureRoute: FailureRoute,
  InlineRoute: InlineRouteWithChildren,
<<<<<<< HEAD
  OverlayRoute: OverlayRouteWithChildren,
=======
  OverlayRoute: OverlayRoute,
>>>>>>> main
  SuccessRoute: SuccessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
